spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false

webdriverpath: C:\Program Files\Google\Chrome\Application\chromedriver.exe
webdriverurl: https://www.esunbank.com/zh-tw/personal/deposit/rate/forex/exchange-rate-chart?Currency=USD/TWD